name: Deploy SkillMatch Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # or your Node version

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build # if using TypeScript or a build step

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/skillmatch-backend
          git pull origin main
          npm install
          npm run build
          pm2 restart server # or node server.js or however you run it
